name: Generate Pacman

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Generate Pacman
        uses: abozanona/pacman-contribution-graph@main
        with:
          github_user_name: jjeanpedro03

      - name: Move and rename SVG (safe)
        run: |
          if [ -d "dist" ]; then
            FILE=$(ls dist/*.svg | head -n 1)
            mv "$FILE" pacman.svg
          else
            echo "dist folder not found"
            exit 1
          fi

      - name: Apply dark theme
        run: |
          FILE="pacman.svg"

          # fundo escuro
          sed -i 's/#ffffff/#0d1117/g' $FILE

          # quadrados vazios escuros
          sed -i 's/#ebedf0/#161b22/g' $FILE

      - name: Commit and push
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

          git checkout -B output
          git add pacman.svg
          git commit -m "update pacman" || echo "no changes"
          git push origin output --force
