name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Baixa o repositório
      - name: Checkout repository
        uses: actions/checkout@v4

      # Gera o snake
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: jjeanpedro03
          outputs: dist/snake.svg?color_snake=#00FFFF&color_dots=#0d1117,#0d1117,#0e4429,#006d32,#26a641,#39d353&background=#0d1117

      # Faz push FORÇADO (resolve seu erro)
      - name: Push snake
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -B output
          git add dist/*
          git commit -m "update snake" || echo "No changes"
          git push origin output --force
