name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # ✅ PASSO 1: baixar o repositório (ESSENCIAL)
      - name: Checkout repository
        uses: actions/checkout@v3

      # ✅ PASSO 2: gerar o snake
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: jjeanpedro03
          outputs: |
            dist/snake.svg?color_snake=cyan&background=transparent

      # ✅ PASSO 3: enviar para branch output
      - name: Push snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "update snake"
          add: "dist/*"
          new_branch: output
