name: Generate Snake

on:
  schedule:
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      # Baixa o repositório
      - name: Checkout repository
        uses: actions/checkout@v3

      # Gera o snake
      - name: Generate snake
        uses: Platane/snk@v3
        with:
          github_user_name: jjeanpedro03
          outputs: |
            dist/snake.svg?color_snake=cyan&color_dots=#161b22,#161b22,#0e4429,#006d32,#26a641,#39d353&background=transparent

      # Faz commit na branch output
      - name: Push snake
        uses: EndBug/add-and-commit@v9
        with:
          message: "update snake"
          add: "dist/*"
          new_branch: output
